/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'duration' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Address = IDL.Record({
  'id' : IDL.Nat,
  'zip' : IDL.Text,
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
});
export const UserProfileResponse = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'blocked' : IDL.Bool,
  'createdAt' : Time,
  'role' : UserRole,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'updatedAt' : Time,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'walletBalance' : IDL.Int,
  'firstName' : IDL.Text,
});
export const ServiceCategory = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'blocked' : IDL.Bool,
  'createdAt' : Time,
  'role' : UserRole,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'updatedAt' : Time,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'walletBalance' : IDL.Int,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAddress' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getActiveServicesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfileResponse)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryWithServices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ServiceCategory, IDL.Vec(Service)))],
      ['query'],
    ),
  'getServiceDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getTopActiveCategories' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ServiceCategory)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileResponse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
  'listServicesByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Service)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveAddress' : IDL.Func([Address], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setDefaultAddress' : IDL.Func([IDL.Nat], [], []),
  'updateCategoryOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'duration' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Address = IDL.Record({
    'id' : IDL.Nat,
    'zip' : IDL.Text,
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const UserProfileResponse = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'blocked' : IDL.Bool,
    'createdAt' : Time,
    'role' : UserRole,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'updatedAt' : Time,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'walletBalance' : IDL.Int,
    'firstName' : IDL.Text,
  });
  const ServiceCategory = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'blocked' : IDL.Bool,
    'createdAt' : Time,
    'role' : UserRole,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'updatedAt' : Time,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'walletBalance' : IDL.Int,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAddress' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getActiveServicesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileResponse)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryWithServices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ServiceCategory, IDL.Vec(Service)))],
        ['query'],
      ),
    'getServiceDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getTopActiveCategories' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceCategory)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileResponse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(ServiceCategory)], ['query']),
    'listServicesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveAddress' : IDL.Func([Address], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setDefaultAddress' : IDL.Func([IDL.Nat], [], []),
    'updateCategoryOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };