/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : bigint,
  'zip' : string,
  'city' : string,
  'userId' : Principal,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'isDefault' : boolean,
  'phone' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Service {
  'id' : bigint,
  'categoryId' : bigint,
  'duration' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'price' : bigint,
}
export interface ServiceCategory {
  'id' : bigint,
  'order' : bigint,
  'name' : string,
  'iconUrl' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'principal' : Principal,
  'referralCode' : string,
  'blocked' : boolean,
  'createdAt' : Time,
  'role' : UserRole,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'updatedAt' : Time,
  'phone' : string,
  'lastName' : string,
  'walletBalance' : bigint,
  'firstName' : string,
}
export interface UserProfileResponse {
  'principal' : Principal,
  'referralCode' : string,
  'blocked' : boolean,
  'createdAt' : Time,
  'role' : UserRole,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'updatedAt' : Time,
  'phone' : string,
  'lastName' : string,
  'walletBalance' : bigint,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Creates a new service category. Admin only.
   */
  'createCategory' : ActorMethod<[string, string], bigint>,
  /**
   * / Creates a new service. Admin only.
   */
  'createService' : ActorMethod<
    [bigint, string, string, bigint, bigint, string],
    bigint
  >,
  /**
   * / Deletes one of the calling user's saved addresses.
   */
  'deleteAddress' : ActorMethod<[bigint], undefined>,
  /**
   * / Deletes a service. Admin only.
   */
  'deleteService' : ActorMethod<[bigint], undefined>,
  /**
   * / Returns active services for a category. Readable by everyone.
   */
  'getActiveServicesByCategory' : ActorMethod<[bigint], Array<Service>>,
  /**
   * / Returns the profile of the calling user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileResponse]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns each category paired with its active services. Readable by everyone.
   */
  'getCategoryWithServices' : ActorMethod<
    [],
    Array<[ServiceCategory, Array<Service>]>
  >,
  /**
   * / Returns details of a single service. Readable by everyone.
   */
  'getServiceDetails' : ActorMethod<[bigint], [] | [Service]>,
  /**
   * / Returns the first `limit` categories. Readable by everyone.
   */
  'getTopActiveCategories' : ActorMethod<[bigint], Array<ServiceCategory>>,
  /**
   * / Returns the profile of any user. Callers may only view their own profile
   * / unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileResponse]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  /**
   * / Returns all saved addresses for the calling user.
   */
  'listAddresses' : ActorMethod<[], Array<Address>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  /**
   * / Lists all service categories. Readable by everyone.
   */
  'listCategories' : ActorMethod<[], Array<ServiceCategory>>,
  /**
   * / Lists active services for a given category. Readable by everyone.
   */
  'listServicesByCategory' : ActorMethod<[bigint], Array<Service>>,
  'requestApproval' : ActorMethod<[], undefined>,
  /**
   * / Adds a new address to the calling user's saved addresses.
   */
  'saveAddress' : ActorMethod<[Address], undefined>,
  /**
   * / Saves (creates or updates) the profile of the calling user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Marks one of the calling user's addresses as the default.
   */
  'setDefaultAddress' : ActorMethod<[bigint], undefined>,
  /**
   * / Updates the display order of a category. Admin only.
   */
  'updateCategoryOrder' : ActorMethod<[bigint, bigint], undefined>,
  /**
   * / Updates an existing service. Admin only.
   */
  'updateService' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];